[package]
name = "atompunk-badge"
version = "0.1.0"
authors = ["yetone <yetoneful@gmail.com>"]

[dependencies]
rocket = "*"
reqwest = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
log = "*"
env_logger = "*"